### ISSUE TITLE
Post date is not show correctly

### ISSUE THREAD

**Issue by WyattZhang** [kAworu/octostrap3#41]
You can see here:  http://wyattzhang.github.io
The time element on post title all shows "ordinal" 

In my  _config.yml the data_format is default 
`date_format: "ordinal"`

The post date shows correctly with default theme, so I guess this may be a bug

Thanks

**Comment by kAworu** [comment]
Documented here http://kaworu.github.io/octostrap3/blog/2015/01/23/octostrap-3-dot-3-1-release/, closing.
