### ISSUE TITLE
Incorrect url

### ISSUE THREAD

**Issue by Semigradsky** [kAworu/octostrap3#45]
In http://kaworu.github.io/octostrap3/
![image](https://cloud.githubusercontent.com/assets/1198848/5974422/3d21d148-a885-11e4-8969-2c933b5ba61a.png)

Request URL:http://kaworu.github.io/javascripts/libs/jXHR.js

**Comment by kAworu** [comment]
See https://github.com/kAworu/octostrap3/blob/ecfe5415d21a376d63c4141d643ba25d53439ac0/source/_includes/asides/github.html#L19 I feel like `{{ root_url }}` does not work. Works fine on line 25 and 32 though. Any idea ?

**Comment by paskal** [comment]
In source code:
`jxhr.src = '{{ root_url}}/javascripts/libs/jXHR.js';`
In HTML source:
`jxhr.src = '/javascripts/libs/jXHR.js';`
Actually you miss a space before `}}`

**Comment by kAworu** [comment]
@paskal 

Did you test by adding the space ? I remember trying with the space and it did not work, but if it does now please feel free to fix it !

**Comment by kAworu** [comment]
Also the "typo" is inherited from the classic theme (see https://github.com/imathis/octopress/blob/master/.themes/classic/source/_includes/asides/github.html#L15). Because last time I checked adding a space did not solve the issue, I left is as-is so to avoid a useless diff with the classic theme (from which we import changes sometimes).

**Comment by paskal** [comment]
In any way I tested this line isn't working:
`jxhr.src = "{{ root_url }}/javascripts/libs/jXHR.js";`
but few lines lower working fine:
`<script src="{{ root_url }}/javascripts/github.js" type="text/javascript"> </script>`

**Comment by kAworu** [comment]
Could it be a bug in liquid ?

**Comment by paskal** [comment]
It seems more like a feature:) I think we could ask them. Later tomorrow I'll write an issue request to them.

**Comment by paskal** [comment]
Hi, @kAworu. Could you please take a look at issue on luquid project? We've got an answer.

**Comment by kAworu** [comment]
@paskal sure.

**Comment by paskal** [comment]
Issue is two years old... and I don't see it by the URL mentioned now, seems fixed somewhere else. Resolving, if you don't mind.
